=== sillsdev/paradigm/src/GAFAWSAnalysisTests/XML/GAFAWS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Randy Regnier (SIL International) -->
<!--W3C Schema generated by XML Spy v3.5 NT (http://www.xmlspy.com)-->
<!-- RandyR, 8 Mar 2002. Added Classes to schema -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xsd:element name="GAFAWSData">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="WordRecords">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="WordRecord" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="Prefixes" minOccurs="0">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element ref="Affix" maxOccurs="unbounded"/>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
										<xsd:element name="Stem">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element ref="Other" minOccurs="0"/>
												</xsd:sequence>
												<xsd:attribute name="id" type="xsd:IDREF" use="required"/>
											</xsd:complexType>
										</xsd:element>
										<xsd:element name="Suffixes" minOccurs="0">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element ref="Affix" maxOccurs="unbounded"/>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
										<xsd:element ref="Other" minOccurs="0"/>
									</xsd:sequence>
									<xsd:attribute name="id" type="xsd:ID" use="required"/>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="Morphemes">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Morpheme" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element ref="Other" minOccurs="0"/>
									</xsd:sequence>
									<xsd:attribute name="id" type="xsd:ID" use="required"/>
									<xsd:attribute name="type" type="xsd:string" use="required"/>
									<xsd:attribute name="startclass" type="xsd:IDREF"/>
									<xsd:attribute name="endclass" type="xsd:IDREF"/>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="AffixSets">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="AffixCooccurrences">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="AffixCooccurrenceSet" minOccurs="0" maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name="Morpheme"  minOccurs="1" maxOccurs="unbounded">
														<xsd:complexType>
															<xsd:attribute name="id" type="xsd:IDREF"/>
														</xsd:complexType>
													</xsd:element>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="AffixNonCooccurrences">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="AffixNonCooccurrenceSet" minOccurs="0" maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name="Morpheme"  minOccurs="1" maxOccurs="unbounded">
														<xsd:complexType>
															<xsd:attribute name="id" type="xsd:IDREF"/>
														</xsd:complexType>
													</xsd:element>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="DistinctSets">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="DistinctSet" minOccurs="0" maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name="Morpheme"  minOccurs="1" maxOccurs="unbounded">
														<xsd:complexType>
															<xsd:attribute name="id" type="xsd:IDREF"/>
														</xsd:complexType>
													</xsd:element>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="SubgraphSets">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="SubgraphSet" minOccurs="0" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="Subgraph"  minOccurs="1" maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name="Morpheme"  minOccurs="1" maxOccurs="unbounded">
														<xsd:complexType>
															<xsd:attribute name="id" type="xsd:IDREF"/>
														</xsd:complexType>
													</xsd:element>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="Classes">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="PrefixClasses">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element ref="Class" minOccurs="0" maxOccurs="unbounded"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="SuffixClasses">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element ref="Class" minOccurs="0" maxOccurs="unbounded"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="Challenges">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Challenge" minOccurs="0" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:attribute name="message" type="xsd:string" use="required"/>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element ref="Other" minOccurs="0"/>
			</xsd:sequence>
			<xsd:attribute name="date" type="xsd:string"/>
			<xsd:attribute name="time" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Class">
		<xsd:complexType>
			<xsd:attribute name="id" type="xsd:ID" use="required"/>
			<xsd:attribute name="name" type="xsd:string"/>
			<xsd:attribute name="isfogbank" type="xsd:string" default="0"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Affix">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Other" minOccurs="0"/>
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:IDREF" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Other">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:any namespace="##any" processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== sillsdev/paradigm/src/GAFAWSAnalysisTests/XML/TestA1A.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by Randy Regnier (SIL International) -->
<GAFAWSData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="E:\fw\Src\WW-GAFAWS\GAFAWSDataLayer\XML\GAFAWS.xsd">
  <WordRecords>
	<WordRecord id="WR1">
	  <Prefixes>
		<Affix id="p4"/>
		<Affix id="p3"/>
	  </Prefixes>
	  <Stem id="R"/>
	  <Suffixes>
		<Affix id="s2"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR2">
	  <Prefixes>
		<Affix id="p3"/>
		<Affix id="p2"/>
	  </Prefixes>
	  <Stem id="R"/>
	  <Suffixes>
		<Affix id="s1"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR3">
	  <Prefixes>
		<Affix id="p4"/>
		<Affix id="p1"/>
	  </Prefixes>
	  <Stem id="R"/>
	  <Suffixes>
		<Affix id="s1"/>
		<Affix id="s2"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR4">
	  <Prefixes>
		<Affix id="p2"/>
		<Affix id="p1"/>
	  </Prefixes>
	  <Stem id="R"/>
	  <Suffixes>
		<Affix id="s2"/>
		<Affix id="s3"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR5">
	  <Prefixes>
		<Affix id="p4"/>
		<Affix id="p23"/>
		<Affix id="p1"/>
	  </Prefixes>
	  <Stem id="R"/>
	  <Suffixes>
		<Affix id="s12"/>
		<Affix id="s3"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR6">
	  <Prefixes>
		<Affix id="p34"/>
		<Affix id="p12"/>
	  </Prefixes>
	  <Stem id="R"/>
	  <Suffixes>
		<Affix id="s1"/>
		<Affix id="s23"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR7">
	  <Prefixes>
		<Affix id="p3"/>
		<Affix id="p12"/>
	  </Prefixes>
	  <Stem id="R"/>
	</WordRecord>
	<WordRecord id="WR8">
	  <Prefixes>
		<Affix id="p34"/>
		<Affix id="p2"/>
	  </Prefixes>
	  <Stem id="R"/>
	</WordRecord>
	<WordRecord id="WR9">
	  <Prefixes>
		<Affix id="p4"/>
		<Affix id="p13"/>
	  </Prefixes>
	  <Stem id="R"/>
	  <Suffixes>
		<Affix id="s13"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR10">
	  <Prefixes>
		<Affix id="p24"/>
		<Affix id="p1"/>
	  </Prefixes>
	  <Stem id="R"/>
	</WordRecord>
	<WordRecord id="WR11">
	  <Prefixes>
		<Affix id="p14"/>
	  </Prefixes>
	  <Stem id="R"/>
	</WordRecord>
  </WordRecords>
  <Morphemes>
	<Morpheme id="R" type="s"/>
	<Morpheme id="p1" type="pfx"/>
	<Morpheme id="p2" type="pfx"/>
	<Morpheme id="p3" type="pfx"/>
	<Morpheme id="p4" type="pfx"/>
	<Morpheme id="p12" type="pfx"/>
	<Morpheme id="p13" type="pfx"/>
	<Morpheme id="p14" type="pfx"/>
	<Morpheme id="p23" type="pfx"/>
	<Morpheme id="p24" type="pfx"/>
	<Morpheme id="p34" type="pfx"/>
	<Morpheme id="s1" type="sfx"/>
	<Morpheme id="s2" type="sfx"/>
	<Morpheme id="s3" type="sfx"/>
	<Morpheme id="s12" type="sfx"/>
	<Morpheme id="s13" type="sfx"/>
	<Morpheme id="s23" type="sfx"/>
  </Morphemes>
  <Classes>
	<PrefixClasses/>
	<SuffixClasses/>
  </Classes>
  <Challenges/>
</GAFAWSData>

=== sillsdev/paradigm/src/GAFAWSAnalysisTests/XML/Mapudungu.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<GAFAWSData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".\GAFAWS.xsd">
  <WordRecords>
	<WordRecord id="WR1">
	  <Stem id="amu" />
	  <Suffixes>
		<Affix id="a" />
		<Affix id="l" />
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR2">
	  <Stem id="amu" />
	  <Suffixes>
		<Affix id="la" />
		<Affix id="a" />
	  </Suffixes>
</WordRecord>
	<WordRecord id="WR3">
	  <Stem id="amu" />
	  <Suffixes>
		<Affix id="no" />
		<Affix id="a" />
		<Affix id="l" />
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR4">
	  <Stem id="amu" />
	  <Suffixes>
		<Affix id="lle" />
		<Affix id="a" />
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR5">
	  <Stem id="amu" />
	  <Suffixes>
		<Affix id="lle" />
		<Affix id="l" />
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR6">
	  <Stem id="amu" />
	  <Suffixes>
		<Affix id="chi" />
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR7">
	  <Stem id="amu" />
	  <Suffixes>
		<Affix id="ki...l" />
		<Affix id="chi" />
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR8">
	  <Stem id="amu" />
	  <Suffixes>
		<Affix id="ki...l" />
		<Affix id="no" />
		<Affix id="chi" />
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR9">
	  <Stem id="amu" />
	  <Suffixes>
		<Affix id="lle" />
		<Affix id="chi" />
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR10">
	  <Stem id="amu" />
	  <Suffixes>
		<Affix id="lle" />
		<Affix id="no" />
		<Affix id="l" />
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR11">
	  <Stem id="amu" />
	  <Suffixes>
		<Affix id="lle" />
		<Affix id="la" />
	  </Suffixes>
	</WordRecord>
  </WordRecords>
  <Morphemes>
	<Morpheme id="amu" type="s" />
	<Morpheme id="a" type="sfx" />
	<Morpheme id="l" type="sfx" />
	<Morpheme id="la" type="sfx" />
	<Morpheme id="no" type="sfx" />
	<Morpheme id="lle" type="sfx" />
	<Morpheme id="chi" type="sfx" />
	<Morpheme id="ki...l" type="sfx" />
  </Morphemes>
  <AffixSets>
	<AffixCooccurrences />
	<AffixNonCooccurrences />
	<DistinctSets />
  </AffixSets>
	<SubgraphSets />
  <Classes>
	<PrefixClasses />
	<SuffixClasses />
  </Classes>
  <Challenges />
</GAFAWSData>

=== sillsdev/paradigm/src/GAFAWSAnalysisTests/XML/RT-OUTtestA2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by Randy Regnier (SIL International) -->
<GAFAWSData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".\GAFAWS.xsd">
  <WordRecords>
	<WordRecord WRID="WR1">
	  <Prefixes>
		<Affix MIDREF="p4"/>
		<Affix MIDREF="p3"/>
	  </Prefixes>
	  <Stem MIDREF="R"/>
	  <Suffixes>
		<Affix MIDREF="s3"/>
		<Affix MIDREF="s4"/>
	  </Suffixes>
	  <Other>
		<clientWordStuff/>
	  </Other>
	</WordRecord>
	<WordRecord WRID="WR2">
	  <Prefixes>
		<Affix MIDREF="p3"/>
		<Affix MIDREF="p2"/>
	  </Prefixes>
	  <Stem MIDREF="R"/>
	  <Suffixes>
		<Affix MIDREF="s2"/>
		<Affix MIDREF="s3"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord WRID="WR3">
	  <Prefixes>
		<Affix MIDREF="p4"/>
		<Affix MIDREF="p1"/>
	  </Prefixes>
	  <Stem MIDREF="R"/>
	  <Suffixes>
		<Affix MIDREF="s1"/>
		<Affix MIDREF="s4"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord WRID="WR4">
	  <Prefixes>
		<Affix MIDREF="p2"/>
		<Affix MIDREF="p1"/>
	  </Prefixes>
	  <Stem MIDREF="R"/>
	  <Suffixes>
		<Affix MIDREF="s1"/>
		<Affix MIDREF="s2"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord WRID="WR5">
	  <Prefixes>
		<Affix MIDREF="p4"/>
		<Affix MIDREF="p23"/>
		<Affix MIDREF="p1"/>
	  </Prefixes>
	  <Stem MIDREF="R"/>
	  <Suffixes>
		<Affix MIDREF="s1"/>
		<Affix MIDREF="s23"/>
		<Affix MIDREF="s4"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord WRID="WR6">
	  <Prefixes>
		<Affix MIDREF="p34"/>
		<Affix MIDREF="p12"/>
	  </Prefixes>
	  <Stem MIDREF="R"/>
	  <Suffixes>
		<Affix MIDREF="s12"/>
		<Affix MIDREF="s34"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord WRID="WR7">
	  <Prefixes>
		<Affix MIDREF="p3"/>
		<Affix MIDREF="p12"/>
	  </Prefixes>
	  <Stem MIDREF="R"/>
	  <Suffixes>
		<Affix MIDREF="s12"/>
		<Affix MIDREF="s3"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord WRID="WR8">
	  <Prefixes>
		<Affix MIDREF="p34"/>
		<Affix MIDREF="p2"/>
	  </Prefixes>
	  <Stem MIDREF="R"/>
	  <Suffixes>
		<Affix MIDREF="s2"/>
		<Affix MIDREF="s34"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord WRID="WR9">
	  <Prefixes>
		<Affix MIDREF="p4"/>
		<Affix MIDREF="p13"/>
	  </Prefixes>
	  <Stem MIDREF="R"/>
	  <Suffixes>
		<Affix MIDREF="s13"/>
		<Affix MIDREF="s4"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord WRID="WR10">
	  <Prefixes>
		<Affix MIDREF="p24"/>
		<Affix MIDREF="p1"/>
	  </Prefixes>
	  <Stem MIDREF="R"/>
	  <Suffixes>
		<Affix MIDREF="s1"/>
		<Affix MIDREF="s24"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord WRID="WR11">
	  <Prefixes>
		<Affix MIDREF="p14"/>
	  </Prefixes>
	  <Stem MIDREF="R"/>
	  <Suffixes>
		<Affix MIDREF="s14"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord WRID="WR12">
	  <Prefixes>
		<Affix MIDREF="p2"/>
		<Affix MIDREF="p3"/>
		<Affix MIDREF="p1"/>
	  </Prefixes>
	  <Stem MIDREF="R"/>
	  <Suffixes>
		<Affix MIDREF="s1"/>
		<Affix MIDREF="s3"/>
		<Affix MIDREF="s2"/>
	  </Suffixes>
	</WordRecord>
  </WordRecords>
  <Morphemes>
	<Morpheme MID="R" type="s">
	  <Other>
		<clientMorphemeStuff/>
	  </Other>
	</Morpheme>
	<Morpheme MID="p1" type="pfx" StartCLIDREF="PP1" EndCLIDREF="PP0"/>
	<Morpheme MID="p2" type="pfx" StartCLIDREF="PP0" EndCLIDREF="PP0"/>
	<Morpheme MID="p3" type="pfx" StartCLIDREF="PP0" EndCLIDREF="PP0"/>
	<Morpheme MID="p4" type="pfx" StartCLIDREF="PP0" EndCLIDREF="PP4"/>
	<Morpheme MID="p12" type="pfx" StartCLIDREF="PP1" EndCLIDREF="PP0"/>
	<Morpheme MID="p13" type="pfx" StartCLIDREF="PP1" EndCLIDREF="PP3"/>
	<Morpheme MID="p14" type="pfx" StartCLIDREF="PP1" EndCLIDREF="PP4"/>
	<Morpheme MID="p23" type="pfx" StartCLIDREF="PP2" EndCLIDREF="PP3"/>
	<Morpheme MID="p24" type="pfx" StartCLIDREF="PP2" EndCLIDREF="PP4"/>
	<Morpheme MID="p34" type="pfx" StartCLIDREF="PP0" EndCLIDREF="PP4"/>
	<Morpheme MID="s1" type="sfx" StartCLIDREF="SP1" EndCLIDREF="SP0"/>
	<Morpheme MID="s2" type="sfx" StartCLIDREF="SP0" EndCLIDREF="SP0"/>
	<Morpheme MID="s3" type="sfx" StartCLIDREF="SP0" EndCLIDREF="SP0"/>
	<Morpheme MID="s4" type="sfx" StartCLIDREF="SP0" EndCLIDREF="SP4"/>
	<Morpheme MID="s12" type="sfx" StartCLIDREF="SP1" EndCLIDREF="SP0"/>
	<Morpheme MID="s13" type="sfx" StartCLIDREF="SP1" EndCLIDREF="SP3"/>
	<Morpheme MID="s14" type="sfx" StartCLIDREF="SP1" EndCLIDREF="SP4"/>
	<Morpheme MID="s23" type="sfx" StartCLIDREF="SP2" EndCLIDREF="SP3"/>
	<Morpheme MID="s24" type="sfx" StartCLIDREF="SP2" EndCLIDREF="SP4"/>
	<Morpheme MID="s34" type="sfx" StartCLIDREF="SP0" EndCLIDREF="SP4"/>
  </Morphemes>
  <Classes>
	<PrefixClasses>
	  <Class CLID="PP1"/>
	  <Class CLID="PP2"/>
	  <Class CLID="PP0" isFogBank="1"/>
	  <Class CLID="PP3"/>
	  <Class CLID="PP4"/>
	</PrefixClasses>
	<SuffixClasses>
	  <Class CLID="SP1"/>
	  <Class CLID="SP2"/>
	  <Class CLID="SP0" isFogBank="1"/>
	  <Class CLID="SP3"/>
	  <Class CLID="SP4"/>
	</SuffixClasses>
  </Classes>
  <Challenges>
	<Challenge message="Prefix data is inconsistent." code="0"/>
	<Challenge message="Suffix data is inconsistent." code="0"/>
  </Challenges>
</GAFAWSData>

=== sillsdev/paradigm/src/GAFAWSAnalysisTests/XML/Huichol.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by Randy Regnier (SIL International) -->
<GAFAWSData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".\GAFAWS.xsd">
  <WordRecords>
	<WordRecord id="WR1">
	  <Prefixes>
		<Affix id="p&amp;"/>
	  </Prefixes>
	  <Stem id="R"/>
	</WordRecord>
	<WordRecord id="WR2">
	  <Prefixes>
		<Affix id="p&amp;"/>
		<Affix id="ka2"/>
	  </Prefixes>
	  <Stem id="R"/>
	</WordRecord>
	<WordRecord id="WR3">
	  <Prefixes>
		<Affix id="ka1"/>
		<Affix id="p&amp;"/>
	  </Prefixes>
	  <Stem id="R"/>
	</WordRecord>
	<WordRecord id="WR4">
	  <Prefixes>
		<Affix id="ka1"/>
		<Affix id="p&amp;"/>
		  <Affix id="ka2"/>
	  </Prefixes>
	  <Stem id="R"/>
	</WordRecord>
	<WordRecord id="WR5">
	  <Prefixes>
		<Affix id="m&amp;"/>
	  </Prefixes>
	  <Stem id="R"/>
	</WordRecord>
	<WordRecord id="WR6">
	  <Prefixes>
		<Affix id="m&amp;"/>
	  </Prefixes>
	  <Stem id="R"/>
	</WordRecord>
	<WordRecord id="WR7">
	  <Prefixes>
		<Affix id="m&amp;"/>
		<Affix id="ka2"/>
	  </Prefixes>
	  <Stem id="R"/>
	</WordRecord>
	<WordRecord id="WR8">
	  <Prefixes>
		<Affix id="ni"/>
	  </Prefixes>
	  <Stem id="R"/>
	</WordRecord>
	<WordRecord id="WR9">
	  <Prefixes>
		<Affix id="ka1"/>
		<Affix id="ni"/>
	  </Prefixes>
	  <Stem id="R"/>
	</WordRecord>
	<WordRecord id="WR10">
	  <Prefixes>
		<Affix id="ka1"/>
		<Affix id="ka2"/>
		  <Affix id="ni"/>
	  </Prefixes>
	  <Stem id="R"/>
	</WordRecord>
	<WordRecord id="WR11">
	  <Prefixes>
		<Affix id="m&amp;"/>
		  <Affix id="ni"/>
	  </Prefixes>
	  <Stem id="R"/>
	</WordRecord>
	  <WordRecord id="WR12">
		  <Prefixes>
			  <Affix id="m&amp;"/>
			  <Affix id="ka2"/>
			  <Affix id="ni"/>
		  </Prefixes>
		  <Stem id="R"/>
	  </WordRecord>
	  <WordRecord id="WR13">
		  <Stem id="R"/>
	  </WordRecord>
	  <WordRecord id="WR14">
		  <Prefixes>
			  <Affix id="ka2"/>
		  </Prefixes>
		  <Stem id="R"/>
	  </WordRecord>
	  <WordRecord id="WR15">
		  <Prefixes>
			  <Affix id="ke"/>
		  </Prefixes>
		  <Stem id="R"/>
	  </WordRecord>
	  <WordRecord id="WR16">
		  <Prefixes>
			  <Affix id="ke"/>
			  <Affix id="ni"/>
		  </Prefixes>
		  <Stem id="R"/>
	  </WordRecord>
  </WordRecords>
  <Morphemes>
	<Morpheme id="R" type="s" />
	<Morpheme id="p&amp;" type="pfx"/>
	<Morpheme id="ka2" type="pfx"/>
	<Morpheme id="ka1" type="pfx"/>
	<Morpheme id="m&amp;" type="pfx"/>
	<Morpheme id="ni" type="pfx"/>
	<Morpheme id="ke" type="pfx"/>
  </Morphemes>
	<AffixSets>
		<AffixCooccurrences />
		<AffixNonCooccurrences />
		<DistinctSets />
	</AffixSets>
  <Classes>
	<PrefixClasses/>
	<SuffixClasses/>
  </Classes>
  <Challenges/>
</GAFAWSData>

=== sillsdev/paradigm/src/GAFAWSAnalysisTests/XML/OUTTestA1.xml
<?xml version="1.0" encoding="utf-8"?>
<GAFAWSData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".\GAFAWS.xsd" date="Friday, October 03, 2003" time="9:48:33 PM">
  <WordRecords>
	<WordRecord id="WR1">
	  <Prefixes>
		<Affix id="p4" />
		<Affix id="p3" />
	  </Prefixes>
	  <Stem MIDREF="R" />
	  <Suffixes>
		<Affix id="s2" />
	  </Suffixes>
	  <Other>
		<XmlElements />
	  </Other>
	</WordRecord>
	<WordRecord id="WR2">
	  <Prefixes>
		<Affix id="p3" />
		<Affix id="p2" />
	  </Prefixes>
	  <Stem id="R" />
	  <Suffixes>
		<Affix id="s1" />
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR3">
	  <Prefixes>
		<Affix id="p4" />
		<Affix id="p1" />
	  </Prefixes>
	  <Stem id="R" />
	  <Suffixes>
		<Affix id="s1" />
		<Affix id="s2" />
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR4">
	  <Prefixes>
		<Affix id="p2" />
		<Affix id="p1" />
	  </Prefixes>
	  <Stem id="R" />
	  <Suffixes>
		<Affix id="s2" />
		<Affix id="s3" />
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR5">
	  <Prefixes>
		<Affix id="p4" />
		<Affix id="p23" />
		<Affix MIDREF="p1" />
	  </Prefixes>
	  <Stem MIDREF="R" />
	  <Suffixes>
		<Affix id="s12" />
		<Affix id="s3" />
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR6">
	  <Prefixes>
		<Affix id="p34" />
		<Affix id="p12" />
	  </Prefixes>
	  <Stem id="R" />
	  <Suffixes>
		<Affix id="s1" />
		<Affix id="s23" />
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR7">
	  <Prefixes>
		<Affix id="p3" />
		<Affix MIDREF="p12" />
	  </Prefixes>
	  <Stem id="R" />
	</WordRecord>
	<WordRecord id="WR8">
	  <Prefixes>
		<Affix id="p34" />
		<Affix id="p2" />
	  </Prefixes>
	  <Stem id="R" />
	</WordRecord>
	<WordRecord id="WR9">
	  <Prefixes>
		<Affix id="p4" />
		<Affix id="p13" />
	  </Prefixes>
	  <Stem id="R" />
	  <Suffixes>
		<Affix id="s13" />
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR10">
	  <Prefixes>
		<Affix id="p24" />
		<Affix id="p1" />
	  </Prefixes>
	  <Stem id="R" />
	</WordRecord>
	<WordRecord id="WR11">
	  <Prefixes>
		<Affix id="p14" />
	  </Prefixes>
	  <Stem id="R" />
	</WordRecord>
  </WordRecords>
  <Morphemes>
	<Morpheme id="R" type="s">
	  <Other>
		<XmlElements />
	  </Other>
	</Morpheme>
	<Morpheme id="p1" startclass="PP1" endclass="PP1" type="pfx" />
	<Morpheme id="p2" startclass="PP2" endclass="PP2" type="pfx" />
	<Morpheme id="p3" startclass="PP3" endclass="PP3" type="pfx" />
	<Morpheme id="p4" startclass="PP4" endclass="PP4" type="pfx" />
	<Morpheme id="p12" startclass="PP1" endclass="PP2" type="pfx" />
	<Morpheme id="p13" startclass="PP1" endclass="PP3" type="pfx" />
	<Morpheme id="p14" startclass="PP1" endclass="PP4" type="pfx" />
	<Morpheme id="p23" startclass="PP2" endclass="PP3" type="pfx" />
	<Morpheme id="p24" startclass="PP2" endclass="PP4" type="pfx" />
	<Morpheme id="p34" startclass="PP3" endclass="PP4" type="pfx" />
	<Morpheme id="s1" startclass="SP1" endclass="SP1" type="sfx" />
	<Morpheme id="s2" startclass="SP2" endclass="SP2" type="sfx" />
	<Morpheme id="s3" startclass="SP3" endclass="SP3" type="sfx" />
	<Morpheme id="s12" startclass="SP1" endclass="SP2" type="sfx" />
	<Morpheme id="s13" startclass="SP1" endclass="SP3" type="sfx" />
	<Morpheme id="s23" startclass="SP2" endclass="SP3" type="sfx" />
  </Morphemes>
	<AffixSets>
		<AffixCooccurrences />
		<AffixNonCooccurrences />
		<DistinctSets />
	</AffixSets>
	<SubgraphSets />
  <Classes>
	<PrefixClasses>
	  <Class id="PP1" />
	  <Class id="PP2" />
	  <Class id="PP3" />
	  <Class id="PP4" />
	</PrefixClasses>
	<SuffixClasses>
	  <Class id="SP1" />
	  <Class id="SP2" />
	  <Class id="SP3" />
	</SuffixClasses>
  </Classes>
  <Challenges />
</GAFAWSData>

=== sillsdev/paradigm/src/GAFAWSAnalysisTests/XML/RT-OUTtestA1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by Randy Regnier (SIL International) -->
<GAFAWSData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".\GAFAWS.xsd">
  <WordRecords>
	<WordRecord id="WR1">
	  <Prefixes>
		<Affix id="p4"/>
		<Affix id="p3"/>
	  </Prefixes>
	  <Stem id="R"/>
	  <Suffixes>
		<Affix id="s2"/>
	  </Suffixes>
	  <Other>
		<clientWordStuff/>
	  </Other>
	</WordRecord>
	<WordRecord id="WR2">
	  <Prefixes>
		<Affix id="p3"/>
		<Affix id="p2"/>
	  </Prefixes>
	  <Stem id="R"/>
	  <Suffixes>
		<Affix id="s1"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR3">
	  <Prefixes>
		<Affix id="p4"/>
		<Affix id="p1"/>
	  </Prefixes>
	  <Stem id="R"/>
	  <Suffixes>
		<Affix id="s1"/>
		<Affix id="s2"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR4">
	  <Prefixes>
		<Affix id="p2"/>
		<Affix id="p1"/>
	  </Prefixes>
	  <Stem id="R"/>
	  <Suffixes>
		<Affix id="s2"/>
		<Affix id="s3"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR5">
	  <Prefixes>
		<Affix id="p4"/>
		<Affix id="p23"/>
		<Affix id="p1"/>
	  </Prefixes>
	  <Stem id="R"/>
	  <Suffixes>
		<Affix id="s12"/>
		<Affix id="s3"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR6">
	  <Prefixes>
		<Affix id="p34"/>
		<Affix id="p12"/>
	  </Prefixes>
	  <Stem id="R"/>
	  <Suffixes>
		<Affix id="s1"/>
		<Affix id="s23"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR7">
	  <Prefixes>
		<Affix id="p3"/>
		<Affix id="p12"/>
	  </Prefixes>
	  <Stem id="R"/>
	</WordRecord>
	<WordRecord id="WR8">
	  <Prefixes>
		<Affix id="p34"/>
		<Affix id="p2"/>
	  </Prefixes>
	  <Stem id="R"/>
	</WordRecord>
	<WordRecord id="WR9">
	  <Prefixes>
		<Affix id="p4"/>
		<Affix id="p13"/>
	  </Prefixes>
	  <Stem id="R"/>
	  <Suffixes>
		<Affix id="s13"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR10">
	  <Prefixes>
		<Affix id="p24"/>
		<Affix id="p1"/>
	  </Prefixes>
	  <Stem id="R"/>
	</WordRecord>
	<WordRecord id="WR11">
	  <Prefixes>
		<Affix id="p14"/>
	  </Prefixes>
	  <Stem id="R"/>
	</WordRecord>
  </WordRecords>
	<Morphemes>
		<Morpheme id="R" type="s">
			<Other>
				<clientMorphemeStuff/>
			</Other>
		</Morpheme>
		<Morpheme id="p1" type="pfx" startclass="PP1" endclass="PP1"/>
		<Morpheme id="p2" type="pfx" startclass="PP2" endclass="PP2"/>
		<Morpheme id="p3" type="pfx" startclass="PP3" endclass="PP3"/>
		<Morpheme id="p4" type="pfx" startclass="PP4" endclass="PP4"/>
		<Morpheme id="p12" type="pfx" startclass="PP1" endclass="PP2"/>
		<Morpheme id="p13" type="pfx" startclass="PP1" endclass="PP3"/>
		<Morpheme id="p14" type="pfx" startclass="PP1" endclass="PP4"/>
		<Morpheme id="p23" type="pfx" startclass="PP2" endclass="PP3"/>
		<Morpheme id="p24" type="pfx" startclass="PP2" endclass="PP4"/>
		<Morpheme id="p34" type="pfx" startclass="PP3" endclass="PP4"/>
		<Morpheme id="s1" type="sfx" startclass="SP1" endclass="SP1"/>
		<Morpheme id="s2" type="sfx" startclass="SP2" endclass="SP2"/>
		<Morpheme id="s3" type="sfx" startclass="SP3" endclass="SP3"/>
		<Morpheme id="s12" type="sfx" startclass="SP1" endclass="SP2"/>
		<Morpheme id="s13" type="sfx" startclass="SP1" endclass="SP3"/>
		<Morpheme id="s23" type="sfx" startclass="SP2" endclass="SP3"/>
	</Morphemes>
	<AffixSets>
		<AffixCooccurrences />
		<AffixNonCooccurrences />
		<DistinctSets />
	</AffixSets>
	<SubgraphSets />
  <Classes>
	<PrefixClasses>
	  <Class id="PP1"/>
	  <Class id="PP2"/>
	  <Class id="PP3"/>
	  <Class id="PP4"/>
	</PrefixClasses>
	<SuffixClasses>
	  <Class id="SP1"/>
	  <Class id="SP2"/>
	  <Class id="SP3"/>
	</SuffixClasses>
  </Classes>
  <Challenges/>
</GAFAWSData>
