=== sillsdev/paradigm/src/GAFAWSAnalysisTests/XML/GAFAWS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Randy Regnier (SIL International) -->
<!--W3C Schema generated by XML Spy v3.5 NT (http://www.xmlspy.com)-->
<!-- RandyR, 8 Mar 2002. Added Classes to schema -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xsd:element name="GAFAWSData">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="WordRecords">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="WordRecord" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="Prefixes" minOccurs="0">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element ref="Affix" maxOccurs="unbounded"/>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
										<xsd:element name="Stem">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element ref="Other" minOccurs="0"/>
												</xsd:sequence>
												<xsd:attribute name="id" type="xsd:IDREF" use="required"/>
											</xsd:complexType>
										</xsd:element>
										<xsd:element name="Suffixes" minOccurs="0">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element ref="Affix" maxOccurs="unbounded"/>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
										<xsd:element ref="Other" minOccurs="0"/>
									</xsd:sequence>
									<xsd:attribute name="id" type="xsd:ID" use="required"/>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="Morphemes">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Morpheme" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element ref="Other" minOccurs="0"/>
									</xsd:sequence>
									<xsd:attribute name="id" type="xsd:ID" use="required"/>
									<xsd:attribute name="type" type="xsd:string" use="required"/>
									<xsd:attribute name="startclass" type="xsd:IDREF"/>
									<xsd:attribute name="endclass" type="xsd:IDREF"/>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="AffixSets">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="AffixCooccurrences">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="AffixCooccurrenceSet" minOccurs="0" maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name="Morpheme"  minOccurs="1" maxOccurs="unbounded">
														<xsd:complexType>
															<xsd:attribute name="id" type="xsd:IDREF"/>
														</xsd:complexType>
													</xsd:element>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="AffixNonCooccurrences">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="AffixNonCooccurrenceSet" minOccurs="0" maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name="Morpheme"  minOccurs="1" maxOccurs="unbounded">
														<xsd:complexType>
															<xsd:attribute name="id" type="xsd:IDREF"/>
														</xsd:complexType>
													</xsd:element>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="DistinctSets">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="DistinctSet" minOccurs="0" maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name="Morpheme"  minOccurs="1" maxOccurs="unbounded">
														<xsd:complexType>
															<xsd:attribute name="id" type="xsd:IDREF"/>
														</xsd:complexType>
													</xsd:element>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="SubgraphSets">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="SubgraphSet" minOccurs="0" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="Subgraph"  minOccurs="1" maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name="Morpheme"  minOccurs="1" maxOccurs="unbounded">
														<xsd:complexType>
															<xsd:attribute name="id" type="xsd:IDREF"/>
														</xsd:complexType>
													</xsd:element>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="Classes">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="PrefixClasses">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element ref="Class" minOccurs="0" maxOccurs="unbounded"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="SuffixClasses">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element ref="Class" minOccurs="0" maxOccurs="unbounded"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="Challenges">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Challenge" minOccurs="0" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:attribute name="message" type="xsd:string" use="required"/>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element ref="Other" minOccurs="0"/>
			</xsd:sequence>
			<xsd:attribute name="date" type="xsd:string"/>
			<xsd:attribute name="time" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Class">
		<xsd:complexType>
			<xsd:attribute name="id" type="xsd:ID" use="required"/>
			<xsd:attribute name="name" type="xsd:string"/>
			<xsd:attribute name="isfogbank" type="xsd:string" default="0"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Affix">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Other" minOccurs="0"/>
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:IDREF" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Other">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:any namespace="##any" processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== sillsdev/paradigm/src/GAFAWSAnalysisTests/XML/TestA1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by Randy Regnier (SIL International) -->
<GAFAWSData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".\GAFAWS.xsd">
  <WordRecords>
	<WordRecord id="WR1">
	  <Prefixes>
		<Affix id="p4"/>
		<Affix id="p3"/>
	  </Prefixes>
	  <Stem id="R"/>
	  <Suffixes>
		<Affix id="s2"/>
	  </Suffixes>
	  <Other>
		<clientWordStuff/>
	  </Other>
	</WordRecord>
	<WordRecord id="WR2">
	  <Prefixes>
		<Affix id="p3"/>
		<Affix id="p2"/>
	  </Prefixes>
	  <Stem id="R"/>
	  <Suffixes>
		<Affix id="s1"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR3">
	  <Prefixes>
		<Affix id="p4"/>
		<Affix id="p1"/>
	  </Prefixes>
	  <Stem id="R"/>
	  <Suffixes>
		<Affix id="s1"/>
		<Affix id="s2"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR4">
	  <Prefixes>
		<Affix id="p2"/>
		<Affix id="p1"/>
	  </Prefixes>
	  <Stem id="R"/>
	  <Suffixes>
		<Affix id="s2"/>
		<Affix id="s3"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR5">
	  <Prefixes>
		<Affix id="p4"/>
		<Affix id="p23"/>
		<Affix id="p1"/>
	  </Prefixes>
	  <Stem id="R"/>
	  <Suffixes>
		<Affix id="s12"/>
		<Affix id="s3"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR6">
	  <Prefixes>
		<Affix id="p34"/>
		<Affix id="p12"/>
	  </Prefixes>
	  <Stem id="R"/>
	  <Suffixes>
		<Affix id="s1"/>
		<Affix id="s23"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR7">
	  <Prefixes>
		<Affix id="p3"/>
		<Affix id="p12"/>
	  </Prefixes>
	  <Stem id="R"/>
	</WordRecord>
	<WordRecord id="WR8">
	  <Prefixes>
		<Affix id="p34"/>
		<Affix id="p2"/>
	  </Prefixes>
	  <Stem id="R"/>
	</WordRecord>
	<WordRecord id="WR9">
	  <Prefixes>
		<Affix id="p4"/>
		<Affix id="p13"/>
	  </Prefixes>
	  <Stem id="R"/>
	  <Suffixes>
		<Affix id="s13"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord id="WR10">
	  <Prefixes>
		<Affix id="p24"/>
		<Affix id="p1"/>
	  </Prefixes>
	  <Stem id="R"/>
	</WordRecord>
	<WordRecord id="WR11">
	  <Prefixes>
		<Affix id="p14"/>
	  </Prefixes>
	  <Stem id="R"/>
	</WordRecord>
  </WordRecords>
  <Morphemes>
	<Morpheme id="R" type="s">
	  <Other>
		<clientMorphemeStuff/>
	  </Other>
	</Morpheme>
	<Morpheme id="p1" type="pfx"/>
	<Morpheme id="p2" type="pfx"/>
	<Morpheme id="p3" type="pfx"/>
	<Morpheme id="p4" type="pfx"/>
	<Morpheme id="p12" type="pfx"/>
	<Morpheme id="p13" type="pfx"/>
	<Morpheme id="p14" type="pfx"/>
	<Morpheme id="p23" type="pfx"/>
	<Morpheme id="p24" type="pfx"/>
	<Morpheme id="p34" type="pfx"/>
	<Morpheme id="s1" type="sfx"/>
	<Morpheme id="s2" type="sfx"/>
	<Morpheme id="s3" type="sfx"/>
	<Morpheme id="s12" type="sfx"/>
	<Morpheme id="s13" type="sfx"/>
	<Morpheme id="s23" type="sfx"/>
  </Morphemes>
	<AffixCooccurrences />
	<AffixNonCooccurrences />
	<DistinctSets />
  <Classes>
	<PrefixClasses/>
	<SuffixClasses/>
  </Classes>
  <Challenges/>
</GAFAWSData>

=== sillsdev/paradigm/src/GAFAWSAnalysisTests/XML/TestB.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by Randy Regnier (SIL International) -->
<GAFAWSData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".\GAFAWS.xsd">
  <WordRecords>
	<WordRecord WRID="WR1">
	  <Prefixes>
		<Affix MIDREF="p4"/>
		<Affix MIDREF="p3"/>
	  </Prefixes>
	  <Stem MIDREF="R"/>
	  <Suffixes>
		<Affix MIDREF="s2"/>
	  </Suffixes>
	  <Other>
		<clientWordStuff/>
	  </Other>
	</WordRecord>
	<WordRecord WRID="WR2">
	  <Prefixes>
		<Affix MIDREF="p3"/>
		<Affix MIDREF="p2"/>
	  </Prefixes>
	  <Stem MIDREF="R"/>
	  <Suffixes>
		<Affix MIDREF="s1"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord WRID="WR3">
	  <Prefixes>
		<Affix MIDREF="p4"/>
		<Affix MIDREF="p1"/>
	  </Prefixes>
	  <Stem MIDREF="R"/>
	  <Suffixes>
		<Affix MIDREF="s1"/>
		<Affix MIDREF="s2"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord WRID="WR4">
	  <Prefixes>
		<Affix MIDREF="p2"/>
		<Affix MIDREF="p1"/>
	  </Prefixes>
	  <Stem MIDREF="R"/>
	  <Suffixes>
		<Affix MIDREF="s2"/>
		<Affix MIDREF="s3"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord WRID="WR5">
	  <Prefixes>
		<Affix MIDREF="p4"/>
		<Affix MIDREF="p23"/>
		<Affix MIDREF="p1"/>
	  </Prefixes>
	  <Stem MIDREF="R"/>
	  <Suffixes>
		<Affix MIDREF="s12"/>
		<Affix MIDREF="s3"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord WRID="WR6">
	  <Prefixes>
		<Affix MIDREF="p34"/>
		<Affix MIDREF="p12"/>
	  </Prefixes>
	  <Stem MIDREF="R"/>
	  <Suffixes>
		<Affix MIDREF="s1"/>
		<Affix MIDREF="s23"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord WRID="WR7">
	  <Prefixes>
		<Affix MIDREF="p3"/>
		<Affix MIDREF="p12"/>
	  </Prefixes>
	  <Stem MIDREF="R"/>
	</WordRecord>
	<WordRecord WRID="WR8">
	  <Prefixes>
		<Affix MIDREF="p34"/>
		<Affix MIDREF="p2"/>
	  </Prefixes>
	  <Stem MIDREF="R"/>
	</WordRecord>
	<WordRecord WRID="WR9">
	  <Prefixes>
		<Affix MIDREF="p4"/>
		<Affix MIDREF="p13"/>
	  </Prefixes>
	  <Stem MIDREF="R"/>
	  <Suffixes>
		<Affix MIDREF="s13"/>
	  </Suffixes>
	</WordRecord>
	<WordRecord WRID="WR10">
	  <Prefixes>
		<Affix MIDREF="p24"/>
		<Affix MIDREF="p1"/>
	  </Prefixes>
	  <Stem MIDREF="R"/>
	</WordRecord>
	<WordRecord WRID="WR11">
	  <Prefixes>
		<Affix MIDREF="p14"/>
	  </Prefixes>
	  <Stem MIDREF="R"/>
	</WordRecord>
  </WordRecords>
  <Morphemes>
	<Morpheme MID="R" type="s"/>
	<Morpheme MID="p1" type="pfx"/>
	<Morpheme MID="p2" type="pfx"/>
	<Morpheme MID="p3" type="pfx"/>
	<Morpheme MID="p4" type="pfx"/>
	<Morpheme MID="p12" type="pfx"/>
	<Morpheme MID="p13" type="pfx"/>
	<Morpheme MID="p14" type="pfx"/>
	<Morpheme MID="p23" type="pfx"/>
	<Morpheme MID="p24" type="pfx"/>
	<Morpheme MID="p34" type="pfx"/>
	<Morpheme MID="s1" type="sfx"/>
	<Morpheme MID="s2" type="sfx"/>
	<Morpheme MID="s3" type="sfx"/>
	<Morpheme MID="s12" type="sfx"/>
	<Morpheme MID="s13" type="sfx"/>
	<Morpheme MID="s23" type="sfx"/>
  </Morphemes>
  <Classes>
	<PrefixClasses/>
	<SuffixClasses/>
  </Classes>
  <Challenges/>
</GAFAWSData>
